version: "3.9"



networks:
  app-network:
    driver: bridge


volumes:
  node_modules_volume:


services:
  nginx:
    image: nginx:stable-alpine

    volumes:
      - './nginx/nginx.dev.conf:/etc/nginx/nginx.conf'
    
    environment:
      - NGINX_MODE=development

    networks:
      - app-network

    ports:
      - "80:80"
  
    depends_on:
      - frontend-dev
      - api


  # * BACK
  api:
    build:
      context: ./api
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    networks:
      - app-network


  # * FRONT
  frontend-dev:
    environment:
      NODE_ENV: development

    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
  
    volumes:
      - ./app:/app
      - node_modules_volume:/app/node_modules

    networks:
      - app-network

    ports:
      - "5173:5173"

